import './globals.css';

import AppProvider from './app-provider';
import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import { Toaster } from '@/components/ui/toaster';
import { cookies } from 'next/headers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const cookieStore = cookies();
	const sessionToken = cookieStore.get('sessionToken');

	return (
		<html lang="en">
			<body className={inter.className}>
				<AppProvider initialSessionToken={sessionToken?.value}>
					{children}
				</AppProvider>
				<Toaster />
			</body>
		</html>
	);
}
